# Generated by Django 4.0.3 on 2022-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0002_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to='photoblog/static/photoblog/'),
        ),
    ]
