# Generated by Django 4.0.3 on 2022-06-08 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 23, 20, 6, 862099)),
        ),
    ]
