# Generated by Django 4.0.3 on 2022-06-09 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0021_post_original_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='original_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 21, 44, 4, 532353)),
        ),
    ]
