# Generated by Django 4.0.3 on 2022-06-16 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0022_remove_post_slug_alter_post_original_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-original_creation_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='original_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 5, 22, 737140)),
        ),
    ]
